# http://wiki.bukkit.org/Plugin_YAML
name: MinecraftUniversalTranslator
version: 0.0.1-SNAPSHOT
description: Facilitates automatic translation in Minecraft.
author: purevoxel

main: com.idynin.MinecraftUniversalTranslator.MinecraftUniversalTranslator
database: true

commands:
  mut:
    description: The Minecraft Universal Translator
    usage: |
      /<command> [parameter]
      Parameters:
        tl <language> - sets target language to <language>
          <language> may be either two letter code or full name
        storecache - stores translation cache to datastore
        clearcache - clears translation cache and datastore
    aliases: [tr, translator]
    permission: MinecraftUniversalTranslator.<command>
    permission-message: You don't have <permission>

permissions:
  MinecraftUniversalTranslator.*:
    description: Grants all permissions of MinecraftUniversalTranslator.
    default: op
    children:
      MinecraftUniversalTranslator.mut: true
      
  MinecraftUniversalTranslator.mut:
    description: The Minecraft Universal Translator
    default: true
