name: idyninMCUniversalTranslator
main: com.idynin.MCUniversalTranslator.MCUniversalTranslatorPlugin
version: 0.1

commands:
  tran:
    description: Translation Command.
    usage: /<command>
    permission: TestPlugin.testplugin
    permission-message: You don't have <permission>
permissions:
  MCUniversalTranslator.manager:
    description: Allow managing Universal Translator.
    default: false