# http://wiki.bukkit.org/Plugin_YAML
name: MinecraftUniversalTranslator
main: com.idynin.MinecraftUniversalTranslator.MinecraftUniversalTranslator
version: 0.0.1-SNAPSHOT
author: idynin
description: Facilitates automatic translation in Minecraft.

commands:
  command1:
    description: description
    usage: /<command> parameters
    permission: MinecraftUniversalTranslator.<command>
    permission-message: You don't have <permission>
  command2:
    description: description
    usage: /<command> parameters
    permission: MinecraftUniversalTranslator.<command>
    permission-message: You don't have <permission>

permissions:
  MinecraftUniversalTranslator.*:
    description: Grants all permissions of MinecraftUniversalTranslator.
    default: op
    children:
      MinecraftUniversalTranslator.command:
        description: Gives permission for command.
